Console.Clear();
Console.Write("Введите координаты точки 1 в 3D :");
double x1 = double.Parse(Console.ReadLine());
double y1 = double.Parse(Console.ReadLine());
double z1 = double.Parse(Console.ReadLine());
Console.Write("Введите координаты точки 2 в 3D :");
double x2 = double.Parse(Console.ReadLine());
double y2 = double.Parse(Console.ReadLine());
double z2 = double.Parse(Console.ReadLine());
double rez = Math.Sqrt(Math.Pow((x1-x2),2)+Math.Pow((y1-y2),2)+Math.Pow((z1-z2),2));
Console.WriteLine($"Длина отрезка {rez:f3}");